#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import copy
import json
import re

base = {
    'schema': 'InsultMarkupLanguage/0.2',
    'refresh_age': 604800000,
    'run_info': {
        'count': 30,
        'startTimeout': 1000,
        'maxTimeout': 30000,
        'timeMultiplier': 1.8,
    },
    'whitelist': [
        "www.foxnews.com", "cnn.com", "www.bbc.com/news",
        "www.bbc.co.uk/news", "www.theguardian.com", "www.theguardian.co.uk",
        "nytimes.com", "facebook.com", "washingtonpost.com", "salon.com",
        "slate.com", "buzzfeed.com", "vox.com", "huffingtonpost.com",
        "wsj.com", "economist.com", "latimes.com", "dallasnews.com",
        "usatoday.com", "denverpost.com", "insidedenver.com", "philly.com",
        "chron.com", "detroitnews.com", "freep.com", "boston.com",
        "newsday.com", "startribune.com", "nypost.com", "ajc.com", "nj.com",
        "sfgate.com", "sfchronicle.com", "azcentral.com", "chicagotribune.com",
        "cleveland.com", "oregonlive.com", "tampatribune.com",
        "signonsandiego.com", "mercurynews.com", "contracostatimes.com",
        "insidebayarea.com", "feedly.com", "reddit.com",
        "drudgereport.com", "theblaze.com", "breitbart.com","ijreview.com",
        "newsmax.com", "wnd.com", "dailycaller.com", "washingtontimes.com",
        "nationalreview.com", "townhall.com", "freerepublic.com",
        "pjmedia.com", "hotair.com", "cnsnews.com", "westernjournalism.com",
        "washingtonexaminer.com", "tpnn.com", "newsbusters.org",
        "twitchy.com", "news.google.com", "npr.org", "cnbc.com", "reuters.com"
    ],
    'breaking': [
        'Trump just a big, fat tardigrade.',
        'Trump White House Wretched Hive of Scum, Villany.',
        'Trump admnistration all crooks and liars.',
        'Scientists conclude nothing Trump says is true.',
        'White House to launch new grift campaign.',
        'White house staffed by joyless, broken husks of human beings.',
        'President presently watching TV.',
        'President golfing.',
        'Presidential red button much smaller than previously claimed.',
        'Presidential hair imported from China.',
        'Oval office window opened in attempt to dissipate Presidential gas attack.',
        'Honestly, you don\'t even want to know.',
        'White House backs up stupid tweets with stupid press conference statements.',
        'White House staffers question life choices.',
        'Nothing really happened today. Stop reading the news.',
        'Wishing Earth would open up and swallow White House is not going to make it happen.',
        'Today is day $days_elapsed of the criminal occupation of the White House.',
        'Keep your head up. We are $perc_complete% done with this crap!',
        'Help! I\'m chained to a computer and forced to write clickbait headlines all day.',
        'And you thought Kelly would make it better?',
        'President doesn\'t like you, either.',
        'Melania captured and returned to White House following daring escape.',
        'America offers Trump as much ice cream as he likes if he\'ll just leave.',
        'President repeats something dumb he heard on Fox.',
        'Experts confirm Donald Trump is bad president, bad person.',
        'Trump administration official dissembles.',
        'President manifestly unfit for presidency.',
        'Sound, Fury, Signify Nothing',
        'World Cruel, Cruel',
        'Uh-oh, we\'re really screwed now.',
        'They\'re all corrupt sh!tbags',
        'President pardons self for any and all crimes he, family, friends commit, or may commit.',
        'Brutal autocrats invite Trump to address annual convention.',
        'Trump doubles down on doubling down. Wait, what? What is this, Vegas?',
        "Oh, my God! We're all gonna die!"
    ],
    'actions': {
        'trump': {
            'default_enabled': True,
            'find_regex': [
                "((Donald|DONALD)\\s*(J\\.?\\s*)?)?(Trump|TRUMP)(?!\\w)", "g"
            ],
            "img_find_regex": [
                "(\\b|_|[0-9])[Tt][Rr][Uu][Mm][Pp](\\b|_|[A-Z]|[0-9])",
                "g"
            ],
            'image_replacement': {
                'html': [
                    'National Disgrace Removed',
                    'Disturbing Imagery Blocked',
                    "You don't want to see what was here.",
                    'Detrumpified',
                ],
                'border': 1,
                'background': [
                    'https://img.buzzfeed.com/buzzfeed-static/static/2015-06/3/15/enhanced/webdr03/enhanced-873-1433359232-20.jpg?downsize=715:*&output-format=auto&output-quality=auto',
                    'https://img.buzzfeed.com/buzzfeed-static/static/2015-06/3/15/enhanced/webdr03/enhanced-859-1433359572-14.jpg?downsize=715:*&output-format=auto&output-quality=auto',
                ]
            },
            'randomize_mode': 'always',
        },
        'pence': {
            'default_enabled': True,
            'find_regex': [
                "\\b((Mike|Michael)\\s*)?Pence(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'alt-right': {
            'default_enabled': True,
            'find_regex': [
                "\\b(?!([Aa]|[Aa]n|[Tt]he)\\s)[Aa]lt[- ][Rr]ight(?!\\w)", "g",
            ],
            'randomize_mode': 'always',
        },
        'bannon': {
            'default_enabled': True,
            'find_regex': [
                # first name and/or middle initial may be present
                "((Steve|Steven|Stephen|STEVE|STEVEN|STEPHEN)\\s*((K\\.?|Kevin|KEVIN)\\s*)?)?(Bannon|BANNON)(?!\\w)", "g"
                # first name and/or middle initial must be present
                # "((Steve|Steven|Stephen|STEVE|STEVEN|STEPHEN)\\s*((K\\.?|Kevin|KEVIN)\\s*)?)(Bannon|BANNON)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'sessions': {
            'default_enabled': False,
            'find_regex': [
                "((Jeff|Jefferson|JEFF|JEFFERSON)\\s*((B\\.?|Beauregard|BEAUREGARD)\\s*)?)?(Sessions|SESSIONS)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'conway': {
            'default_enabled': False,
            'find_regex': [
                "((KELLYANNE|Kellyanne)\\s*)?(Conway|CONWAY)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'spicer': {
            'default_enabled': False,
            'find_regex': [
                "((SEAN|Sean)\\s*)?(SPICER|Spicer)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'ryan': {
            'default_enabled': False,
            'find_regex': [
                "((SPEAKER|Speaker)\\s)?((Paul|PAUL)\\s*)?(RYAN|Ryan)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'gorsuch': {
            'default_enabled': False,
            'find_regex': [
                "((JUSTICE|Justice)\\s)?((Neil|NEIL)\\s*)?(GORSUCH|Gorsuch)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'mcconnell': {
            'default_enabled': False,
            'find_regex': [
                "((SENATOR|Senator)\\s)?((ADDISON|Addison)\\s)?((Mitch|MITCH|Mitchell|MITCHELL)\\s*)?(McConnell|MCONNELL)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'breitbart': {
            'default_enabled': False,
            'find_regex': [
                "Breitbart(?!\\w)", "gi"
            ],
            'randomize_mode': 'always',
        },
        'shuckabee': {
            'default_enabled': False,
            'find_regex': [
                "((SARAH|Sarah)\\s)?(HUCKABEE|Huckabee)\\s(SANDERS|Sanders)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'kelly': {
            'default_enabled': False,
            'find_regex': [
                "((GENERAL|General)\\s)?((JOHN|John)\\s)((Francis|F\.)\\s)?(KELLY|Kelly)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'devos': {
            'default_enabled': False,
            'find_regex': [
                "((Elisabeth Dee|Betsy)\\s)?DeVos(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'pai': {
            'default_enabled': False,
            'find_regex': [
                "(Ajit\\s)?Pai(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'kavanaugh': {
            'default_enabled': False,
            'find_regex': [
                "((Justice|JUSTICE)\\s)?((Brett|BRETT)\\s)?((Michael|MICHAEL)\\s)?(Kavanaugh|KAVANAUGH)(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'giuliani': {
            'default_enabled': False,
            'find_regex': [
                "((Rudy|Rudolph)\\s)?Giuliani(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'ivanka': {
            'default_enabled': False,
            'find_regex': [
                "(Ivana Marie|Ivanka)(\\s?Trump(?!\\w))?", "g"
            ],
            'randomize_mode': 'always',
        },
        'hannity': {
            'default_enabled': False,
            'find_regex': [
                "(Sean\\s)?Hannity(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'zuckerberg': {
            'default_enabled': False,
            'find_regex': [
                "(Mark\\s)?Zuckerberg(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'dorsey': {
            'default_enabled': False,
            'find_regex': [
                "Jack\\sDorsey(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
        'mclaughlin': {
            'default_enabled': False,
            'find_regex': [
                "John\\sMcLaughlin(?!\\w)", "g"
                "McLaughlin\\s(([Aa]nd|&)\\sAssociates(?!\\w)", "g"
            ],
            'randomize_mode': 'always',
        },
    },
}

matic = {
    'trump': {
        'recipe': ['a','a','b'],
        'clean' : {
            'slots': {
                'a': [
                    'Loofa-Faced',
                    'Ferret-Wearing',
                    'Apricot',
                    'Gaffe-Prone',
                    'Angry',
                    'Unrepentant',
                    'Short-Fingered',
                    'Idiotic',
                    'Cheeto-Hued',
                    'Gender-Threatened',
                    'Authoritarian',
                    'Seething',
                    'Sun-Dried',
                    'Marmalade',
                    'Tangerine',
                    'Fart-Infused',
                    'Melting',
                    'Deflated',
                    'Soggy',
                    'Pee-Splattered',
                    'Racist',
                    'Man-Shaped',
                    'Swollen',
                    'Dusty',
                    'Yellowing',
                    'Enraged',
                    'Decomposing',
                    'Lumbering',
                    'Orange',
                    'Sexist',
                    'Bewildered',
                    'Flatulent',
                    'Narcissistic',
                    'Molding',
                    'Malignant',
                    'Screaming',
                    'Neon-Tinted',
                    'Sticky',
                    'Gold-Painted',
                    'Nacho-Flavored',
                    'Unkempt',
                    'Fossilized',
                    'Noted',
                    'Mutant',
                    'Spittle-Flecked',
                    'Rotting',
                    'Manchurian',
                    'Gilded',
                    'Stubby-Fingered',
                    'Self-Absorbed',
                    'Toupee-Wearing',
                    'Triple-Chinned',
                    'Xenophobic',
                    'Dessicated',
                    'Regurgitated',
                    'Evil',
                    'Moldering',
                    'Putrescent',
                    'Demonic',
                    'Rage-Addled',
                    'Bewigged',
                    'Industrial-Sized',
                    'Spray-Tanned',
                    'Gelatinous',
                    'Fetid',
                    'Toxic',
                    'Decaying',
                    'Furious',
                    'Mango',
                    'Sociopathic',
                    'Saffron',
                    'Neon',
                    'Vacuous',
                    'Witless',
                    'Yellow',
                    'Day-Glo',
                    'Chicken-Necked',
                    'Deranged',
                    'Desperate',
                    'Vacuous',
                    'Five-Deferment',
                    'Chicken-Eyed',
                    'Slobbering',
                    'Syphilitic',
                    'Cancerous',
                    'Vain',
                    'Impeached',
                ],
                'b': [
                    'Fart',
                    'Goldfish',
                    'Git',
                    'Teratoma',
                    'Dishrag',
                    'Lunatic',
                    'Jack-O-Lantern',
                    'Creamsicle',
                    'Faux Luxury Brand',
                    'Tycoon',
                    'Incest Ponderer',
                    'Birther',
                    'Steak Purveyor',
                    'Christmas Ham',
                    'Vulgarian',
                    'Gingerbread Man',
                    'Tribble',
                    'Adulterer',
                    'Tantrum Thrower',
                    'Paint Factory Explosion',
                    'Shag Carpet',
                    'Hernia Mass',
                    'Tomato',
                    'Blobfish',
                    'Pig Carcass',
                    'Racist',
                    'Comb-Over',
                    'Bloviator',
                    'Meat Wad',
                    'Bag of Flour',
                    'Ear of Corn',
                    'Parody',
                    'Pond Scum',
                    'Troll',
                    'Clown',
                    'Burlap Sack',
                    'Bag of Toxic Sludge',
                    'Trash Fire',
                    'Sno Cone',
                    'Rancid Egg White',
                    'Fermented Pee',
                    'Sack of Rancid Peeps',
                    'Hairpiece',
                    'Pumpkin Pie',
                    'Dishrag',
                    'Yam',
                    'Gak Spill',
                    'Microbe',
                    'Orangutan',
                    'Chester Cheeta Impersonator',
                    'Tardigrade',
                    'Poop',
                    'Landfill',
                    'Orange Julius',
                    'Julius Caesar',
                    'Wound',
                    'Block of Cheddar',
                    'Golem',
                    'Wasp Exoskeleton',
                    'Ham Hock',
                    'Spam',
                    'Carcass',
                    'Leather Couch',
                    'Hot Dog Casing',
                    'Earthworm Gizzard',
                    'Masticated Gristle',
                    'Scab',
                    'Hobgoblin',
                    'Radioactice Skunk',
                    'Horsehair Mattress',
                    'Corn Chip',
                    'Cheez Whiz Mass',
                    'Bog Man',
                    'Cheese Wedge',
                    'Rancid Beef',
                    'Roadside Billboard',
                    'Hate-Balloon',
                    'Rumpelstilstkin',
                    'Self-Tanning Enthusiast',
                    'Fetus',
                    'Wad of Gak',
                    'Tumor',
                    'Chicken Breast',
                    'Disappointment',
                    'Toddler',
                    'Fascist',
                    'Lamprey Eeel',
                    'Tangerine-Tinted',
                    'Craigslist Sofa',
                    'Troll Doll',
                    'Muppet',
                    'Ferret',
                    'Numpty',
                    'Plum',
                    'Führer',
                    'Baby',
                    'Racist',
                    'Embarrassment',
                    'Circus Peanut',
                    'Dingleberry',
                    'Babadook',
                    'Tycoon',
                    'Carrot',
                    'Fart',
                    'Volcano',
                    'Pile of Orange Peels',
                    'Pumpkin',
                    'Manchild',
                    'Monorail Salesman',
                    'Viagra Advertisement',
                    'Ball of Spite',
                    'Twit',
                    'Traffic Cone',
                    'Popsicle',
                    'Wombat',
                    'Opposum Testicle',
                    'Digested Burrito',
                    'Drain Hair',
                    'Marshmallow',
                    'Litter Box',
                    'Blurg',
                    'Carbuncle',
                    'Dog Turd',
                    'Rooster',
                    'Blobfish',
                    'Heap',
                    'Scabies Outbreak',
                    'Sack of Chicken Fat',
                    'Staph Infection',
                    'Algae Bloom',
                    'Dorito',
                    'Mucous Plug',
                    'Fumigation Tent',
                    'Cheez-It',
                    'Kabocha Squash',
                    'Smushed Caterpillar',
                    'Grand Mal Seizure',
                    'Postule',
                    'Caligula',
                    'Der Gropenführer',
                    "Ceaușescu",
                    "Pinochet",
                    "Torquemada",
                    'Mussolini',
                    'Elmer Fudd',
                    'Emperor McTinyhands',
                    'Narcissist',
                    'Emetic',
                    'Marionette',
                    'Oompa-Loompa',
                    'Circus Peanut',
                    'Abscess',
                    'Trash Can',
                    'Genital Wart',
                    'Menace',
                    'Voldemort',
                    'Dotard',
                    'Cheeto',
                    '💩', # poo emoji
                    'Scobberlotcher',
                    'Draft Dodger',
                    'Brat',
                    'Barnacle',
                    'Pigfart',
                    'Traitor',
                    'Genital Wart',
                    'Chump',
                ],
                "shka": [
                    'Artless',
                    'Bawdy',
                    'Beslubbering',
                    'Bootless',
                    'Churlish',
                    'Cockered',
                    'Clouted',
                    'Craven',
                    'Currish',
                    'Dankish',
                    'Dissembling',
                    'Droning',
                    'Errant',
                    'Fawning',
                    'Fobbing',
                    'Froward',
                    'Frothy',
                    'Gleeking',
                    'Goatish',
                    'Gorbellied',
                    'Impertinent',
                    'Infectious',
                    'Jarring',
                    'Loggerheaded',
                    'Lumpish',
                    'Mammering',
                    'Mangled',
                    'Mewling',
                    'Paunchy',
                    'Pribbling',
                    'Puking',
                    'Puny',
                    'Qualling',
                    'Rank',
                    'Reeky',
                    'Roguish',
                    'Ruttish',
                    'Saucy',
                    'Spleeny',
                    'Spongy',
                    'Surly',
                    'Tottering',
                    'Unmuzzled',
                    'Vain',
                    'Venomed',
                    'Villainous',
                    'Warped',
                    'Wayward',
                    'Weedy',
                    'Yeasty',
                ],
                "shkb": [
                    'Base-court',
                    'Bat-fowling',
                    'Beef-witted',
                    'Beetle-headed',
                    'Boil-brained',
                    'Clapper-clawed',
                    'Clay-brained',
                    'Common-kissing',
                    'Crook-pated',
                    'Dismal-dreaming',
                    'Dizzy-eyed',
                    'Doghearted',
                    'Dread-bolted',
                    'Earth-vexing',
                    'Elf-skinned',
                    'Fat-kidneyed',
                    'Fen-sucked',
                    'Flap-mouthed',
                    'Fly-bitten',
                    'Folly-fallen',
                    'Fool-born',
                    'Full-gorged',
                    'Guts-griping',
                    'Half-faced',
                    'Hasty-witted',
                    'Hedge-born',
                    'Hell-hated',
                    'Idle-headed',
                    'Ill-breeding',
                    'Ill-nurtured',
                    'Knotty-pated',
                    'Milk-livered',
                    'Motley-minded',
                    'Onion-eyed',
                    'Plume-plucked',
                    'Pottle-deep',
                    'Pox-marked',
                    'Reeling-ripe',
                    'Rough-hewn',
                    'Rude-growing',
                    'Rump-fed',
                    'Shard-borne',
                    'Sheep-biting',
                    'Spur-galled',
                    'Swag-bellied',
                    'Tardy-gaited',
                    'Tickle-brained',
                    'Toad-spotted',
                    'Unchin-snouted',
                    'Weather-bitten',
                ],
                "shkc": [
                    'Apple-john',
                    'Baggage',
                    'Barnacle',
                    'Bladder',
                    'Boar-pig',
                    'Bugbear',
                    'Bum-bailey',
                    'Canker-blossom',
                    'Clack-dish',
                    'Clotpole',
                    'Coxcomb',
                    'Codpiece',
                    'Death-token',
                    'Dewberry',
                    'Flap-dragon',
                    'Flax-wench',
                    'Flirt-gill',
                    'Foot-licker',
                    'Fustilarian',
                    'Giglet',
                    'Gudgeon',
                    'Haggard',
                    'Harpy',
                    'Hedge-pig',
                    'Horn-beast',
                    'Hugger-mugger',
                    'Joithead',
                    'Lewdster',
                    'Lout',
                    'Maggot-pie',
                    'Malt-worm',
                    'Mammet',
                    'Measle',
                    'Minnow',
                    'Miscreant',
                    'Moldwarp',
                    'Mumble-news',
                    'Nut-hook',
                    'Pigeon-egg',
                    'Pignut',
                    'Puttock',
                    'Pumpion',
                    'Ratsbane',
                    'Scut',
                    'Skainsmate',
                    'Strumpet',
                    'Varlot',
                    'Vassal',
                    'Whey-face',
                    'Wagtail',
                ],
            },
        },
        'dirty': {
            'slots': {
                'a': [
                ],
                'b': [
                    'Fart Basket',
                    'Shit Whistle',
                    'Turd Helmet',
                    'Piss Weasel',
                    'Fucknugget',
                    'Bunglecunt',
                    'Ass Clown',
                    'Shitgibbon',
                    'Dipshit',
                    'Asshat',
                    'Cockwomble',
                    'Ballbag',
                    'Jizztrumpet',
                    'Cocksplat',
                    'Fucktrumpet',
                    'Anus',
                    'Turd',
                    'Condom',
                    'Herpe Sore',
                    'Nutsack',
                    'Ballbag',
                    'Butthole',
                    'Queef',
                    'Penis',
                    'Buttplug',
                    'Chode',
                    'Oracle of Dipshittery',
                    'Attention Whore',
                    'Huckster',
                    'Sphincterlips',
                ],
                'shka': [ ],
                'shkb': [ ],
                'shkc': [ ],
            },
        }
    }
}

monikers = {
  'trump': {
    'clean': [
      "Gaffe-Prone Lunatic",
      "Human-Toupee Hybrid",
      "Decomposing Jack-O-Lantern",
      "Angry Creamsicle",
      "The Kindest, Bravest, Warmest, Most Wonderful Human Being You'll Ever Know in Your Life",
      "Walking Faux Luxury Brand",
      "Real-Estate Tycoon with Simple, Stupid Plan to Defeat ISIS",
      "Self-Proclaimed Ponderer of Incest",
      "Wall Construction Expert",
      "Frequent Provider of Unsolicited Judgements Regarding Female Attractiveness",
      "Unrepentant Birther",
      "Serial Propagator of Demonstrable Falsehoods",
      "Harkener to Unspecified Moment of American Greatness",
      "Master of Zero-Sum Business Deals",
      "Purveyor of Lousy Steak",
      "Angrily Reanimated Christmas Ham",
      "Short-Fingered Vulgarian",
      "Weirdly Authoritarian Gingerbread Man",
      "Traditional Values Adulterer with Two Ex-Wives",
      "Rage Tribble",
      "Unconvincing Presidential Simulation",
      "Scab You Wish You Hadn't Picked",
      "Idiot Media Savant",
      "Fiberglass-Topped Tantrum Thrower",
      "Used Q-tip",
      "Idiot Magnet",
      "Gender-Threatened Lead Paint Factory Explosion",
      "70's-Vintage Umber Shag Carpet",
      "Cheeto Jesus",
      "Bone-in Ham",
      "Four-Time Bankruptcy Filer and Seething Hernia Mass",
      "Sun-Dried Tomato",
      "Adult Blobfish",
      "Deflated Football",
      "Fart-Infused Lump of Raw Meat",
      "Melting Pig Carcass",
      "Disgraced Racist",
      "Talking Comb-Over",
      "Human Equivalent of Cargo Pants that Zip Away into Shorts",
      "Cheeto-Dusted Bloviator",
      "Fuzzy Meat-Wad",
      "Bag of Flour",
      "Man Who Cherishes Women",
      "Future Leader of the Free World",
      "Decomposing Ear of Corn",
      "Own Best Parody",
      "Rich Idiot Willing to Allow Garbage to Fall Out of His Mouth Without Batting a Single Golden Lash",
      "Pond Scum",
      "Noted Troll",
      "Class Clown that Everyone Wishes Would Be Quiet and Let The Class Learn",
      "Melting Businessman",
      "Wax Museum Figure on a Very Hot Day",
      "Soggy Burlap Sack",
      "Bag of Toxic Sludge",
      "President and Ruler for Life",
      "Brightly Burning Trash Fire",
      "Great Judgement-Haver",
      "Man-Sized Sebaceous Cyst",
      "Enlarged Pee-Splattered Sno Cone",
      "Empty Popcorn Bag Rotting in the Sun",
      "Man-Shaped Asbestos Insulation Board",
      "Hair Plug Swollen with Rancid Egg Whites",
      "Inside-Out Lower Intestine",
      "Dusty Barrel of Fermented Peepee",
      "Usually Reasonable Burlap Sack Full of Rancid Peeps",
      "Presidential Candidate and Bargain Bin Full of Yellowing Jean-Claude Van Damme Movies",
      "Hairpiece Come to Life",
      "Normal-Looking Human Man and Entirely Credible Choice as Future Leader of the Free World",
      "Decomposing Pumpkin Pie Inhabited by Vicious Albino Squirrels",
      "Dishrag that on Closer Inspection is Alive with Maggots",
      "Lead Paint Factory Explosion",
      "Candied Yam Riddled with Moldy Spider Carcasses",
      "Enraged Gak Spill",
      "Shriveled Pinto Bean You Had to Pluck out of Your Chipotle Burrito Basket",
      "Human-Sized Infectious Microbe",
      "Poorly-Trained Circus Organgutan",
      "Chester Cheetah Impersonator",
      "Lumbering Human-Size Tardigrade",
      "Tiny Piece of Dried Cat Poop that You Found in Your Rug",
      "Seagull Dipped in Tikka Masala",
      "Bursting Landfill of Municipal Solid Waste",
      "Mountain of Rotting Whale Blubber",
      "Sputum-Filled Orange Julius",
      "Orange Julius Caesar",
      "Gangrenous Gaping Wound",
      "Racist, Sexist Block of Aged Cheddar",
      "Oversized Wasp Exoskeleton Stuffed with Old Mustard",
      "Neo-Fascist Real Estate Golem",
      "Abandoned Roadside Ham Hock",
      "Bewildered, Golden-Helmeted Astronaut Who’s Just Landed on This Planet from a Distant Galaxy",
      "Monument to Human Hubris Crafted out of Rotting Spam",
      "Walking Pile of Reanimated Roadkill",
      "Heaving Carcass",
      "Stately Hot Dog Casing",
      "Flatulent Leather Couch",
      "Swollen Earthworm Gizzard",
      "Narcissistic Bowl of Rotten Gazpacho",
      "Yellowing Hunk of Masticated Gristle",
      "Human/Komodo Dragon Hybrid",
      "Blackening Scab Artfully Hiding in Your Raisin Bran",
      "“Taco truck”",
      "Man Who Became the First Hobgoblin to Enter The White House",
      "Pair of Chapped Lips Superglued to a Hairball",
      "Horsehair Mattress Stuffed with Molding Copies of Hustler",
      "Malignant Corn Chip",
      "Human Kinder Egg Whose Inner Surprise is a Tiny Pebble of Rat Shit",
      "The Sculpture your Three-Year-Old Made out of Soggy Ground-Up Goldfish Snacks",
      "Man with the Hair of a Radioactive Skunk",
      "Roiling Cheez Whiz Mass",
      "Cryogenically Frozen Bog Man",
      "Glistening, Shouting Gristle Mass with a History of Saying Terrible and Stupid Things",
      "Screaming Giant Cheese Wedge",
      "250-pound Accumulation of Rancid Beef",
      "Day-Glo Roadside Billboard About Jock Itch",
      "Temperamental Gelatinous Sponge",
      "Sentient Hate-Balloon",
      "Rumpelstiltskin Inflated with a Bike Pump and Filled with Bacteria",
      "Self-Tanning Enthusiast",
      "Enraged, Bewigged Fetus Blown up to Nightmarish Size",
      "Parental Pile of Burnt Organic Material",
      "Human-Shaped Wad of Gak",
      "Walking Irradiated Tumor",
      "Uncooked Chicken Breast",
      "KKK Rally Port-a-Potty Holding Tank",
      "Neon-Tinted Hellion",
      "Plentiful Field of Dung Piled into the Shape of a President",
      "Malfunctioning Wind Turbine",
      "Seeping Fleabag",
      "Sloshing Styrofoam Takeout Container Filled with Three-Day-Old Mac and Cheese",
      "Sticky, Grabby, Cheeto-Hued Toddler with No Sense of Adult Deportment",
      "Figurative Rubber, and also Literal Rubber",
      "Carnivorous Plant Watered with Irradiated Bat Urine",
      "Sentient Waste Disposal Plant",
      "Disappointment",
      "Poorly-Drawn Fascist",
      "Racist Teratoma",
      "Lamprey Eel Spray-Painted Gold",
      "Hair That You Pluck, Causing a Cluster of Hairs to Sprout in Its Place",
      "Sunken, Corroding Soufflé",
      "Nacho Cheese Golem",
      "Undead Tangerine",
      "Cartoon Representation of Irritable Bowel Syndrome in a Pharmaceutical Ad",
      "Fossilized Meatball",
      "Horking Mole-Creature Suffering from Radioactive Spray-Tan",
      "Tattered Craigslist Sofa",
      "Full-Grown Monopoly Dog Carefully Balancing a Spongecake Atop His Head",
      "Play-Doh Factory Explosion",
      "New Superfood Made of Finely-Ground Clown Wigs",
      "Unkempt Troll Doll Found Floating Facedown in a Tub of Rancid Beluga Caviar",
      "Cheeto-Faced Ferret",
      "Orange Muppet",
      "Mangled Apricot Hellbeast",
      "Little Gloves",
      "Numpty",
      "Weapons-Grade Plum",
      "Hair Führer",
      "Man-Baby",
      "Ambitious Corn Dog that Escaped from the Concession Stand at a Rural Alabama Fairground, Stole an Unattended Wig, Hopped a Freight Train to Atlantic City and Never Looked Back",
      "Ugly Racist",
      "Wealthy Inheritor Disguised as Successful Businessman",
      "National Embarrassment",
      "Wart We Can't Freeze Off Until November 2020",
      "Microwaved Circus Peanut",
      "Talking Dingleberry",
      "Republican Babadook",
      "El Caudillo de Mar-a-Lago",
      "Shouting, Rotting Papaya",
      "Impotent Orangutan",
      "Famed Shouting Tycoon",
      "Mutant Carrot",
      "Spittle-Flecked Carrot",
      "Epic Fart that Just Won't Dissipate",
      "Gibberish Volcano",
      "Shaved Tribble",
      "Pile of Rotten Orange Peels in a Suit",
      "Rotting Pumpkin",
      "Deplorables Coach",
      "Putin Puppet",
      "Projector-in-Chief",
      "Soon-to-be-Fired Reality Show Contestant",
      "Unreliable Narrator of Awful Story",
      "Biff Tannen",
      "Swirling Black Hole that Eats Good Sense",
      "Self-Avowed Perpetrator of Sexual Assault",
      "President Worse Than W, Despite How Improbable That Used to Sound",
      "Sociopathic Operating System Installed on a Frightened Child",
      "Everything Wrong with America, Made into Living Flesh",
      "Manchurian Combover",
      "Cheeto Benito",
      "Scammer-in-Chief",
      "Gigantic Rubbery Manchild",
      "Pompous Suit Balloon",
      "Two-bit Monorail Salesman",
      "Self-Absorbed Git",
      "Gilded Walking Viagra Advertisement",
      "Professional Fraudster",
      "Toupee-Wearing Ball of Spite",
      "Uncooked Bread Dough",
      "Stubby-Fingered Coatfart",
      "World's Most Easily Insulted Fascist Buffoon",
      "Triple-Chinned Bull in a Nuclear China Shop",
      "Trumplethinskin",
      "Twitter Twit",
      "Human Traffic Cone",
      "Dog that Caught the Car",
      "Thin-Skinned Idiot with Nuclear Codes",
      "Grifter-in-Chief",
      "Sentient Caps-Lock Button",
      "Xenophobic Sweet Potato",
      "Batman Villain",
      "Rome Burning, in Man Form",
      "Buffalo Wing that Fell in a Urinal",
      "America's Back Mole",
      "Rain Man of Manipulative Bullshit",
      "World's Largest Troll Doll",
      "Melting Orange Popsicle",
      "Dessicated, Hollowed-Out Pumpkin Stuff With Wasps",
      "Rusted Refrigerator Left in The Sun Until Its Contents Rot And Swell Into A Noxious, Congealed Mass",
      "Regurgitated Wombat",
      "Moldy Pumpkin Spite Latte",
      "Tax-Avoidant Opossum Testicle",
      "Shrieking Carbuncle in a Red Power Tie",
      "Chipotle Burrito Taken to Its Natural, Digested Conclusion",
      "Evil Toddler",
      "Clump of Moldering Drain Hair",
      "Inlfated Pig Stomach Full of Rotten Pierogi",
      "Flatulent Butternut Squash",
      "Putrescent Orange Marshmallow",
      "Pilonidal Cyst",
      "Sexist Sentient Carrot",
      "Abandoned Cruise Ship Full of People Afflicted with Norovirus",
      "Bruised Yam",
      "Overflowing Litter Box",
      "Shaved Bear",
      "Demonic, Racist Goldfish",
      "Long and Thunderous Fart in a Stalled Elevator",
      "Rancid Halloween Oreo Filling",
      "Rage-Addled Oompa Loompa",
      "Bewigged Swollen Gall Bladder",
      "Wheezing Blurg from Endor's Forest Moon",
      "Inflamed Carbuncle",
      "Diet of Templeton The Rat",
      "Soggy Cracker Spread with Spoiled Shrimp Compote",
      "Industrial-Sized Wastebasket in a Clip-On Tie",
      "Impacted Molar",
      "Bag of Hot Garbage Moldering in the Summer Sun",
      "Dry Creek Bed Mysteriously Studded with Dog Turds",
      "Haunted Bidet",
      "Yellowing Mop Dripping with an Unidentifiable, Viscous Fluid",
      "Anthropomorphic Lie",
      "Rooster Who Wandered Into the House and Has to be Restrained Beneath a Metal Wastebasket",
      "Political Equivalent of One of Those Mutant Factory Farm Chickens with Breasts So Big It Can't Walk",
      "Spray-Tanned Blobfish",
      "Parking Cone with Emotional Issues",
      "Moldy Prawn Burrito",
      "Gelatinous Heap",
      "Horrible Man with Hair Like Used Dental Floss and Ideas That Thread The Definition of Democracy",
      "Hexed Tub of Velveeta That's Been Brought to Life and Won't Stop Screaming Racist Insults",
      "Scabies Outbreak in Your Freshman Dorm",
      "Fetid Pooh-Face",
      "Floopy Sack of Rancid Chicken Fat",
      "Cicada Husk Dipped in Fermenting Carrot Soup",
      "Cirrhotic Cheetah Liver Dusted in Gold Leaf",
      "Walking Staph Infection",
      "Large Orange Baby",
      "Besuited Chucky Doll",
      "Objectively Horrible Person",
      "Toxic Algae Bloom",
      "Spicy Asbestos-Flavored Dorito",
      "Snot-Flavored Jelly Bean with Frightening Power and Influence",
      "Decaying, Hollowed-Out Tree Trunk That Houses a Family of Malnourished Possums",
      "Enlarged Brick of Spittle-Flecked Crisco",
      "Gold-Tipped Mucous Plug",
      "Melted Claymation Villain",
      "Unwashed Fumigation Tent",
      "One of Those Piles of Sand by The Highway",
      "Moldering Cheez-It",
      "Hunk of Beef Jerky That Rolls Under The Couch And Is Left to Harden, Becoming Covered in Dust and Cat Hair Until a Cockroach Takes it Back to Its Lair and Makes It His Wife",
      "Three Bigoted Baby Muppets Stacked On Top of Each Other",
      "Half-Melted Pile of Candy Corn from Halloween '83",
      "Giant Mound of Hardened Cheez Whiz",
      "Smushed up Caterpillar Your 6-Year-Old Brother Set On Fire With a Magnifying Glass",
      "Rotten Kabocha Squash",
      "Orange Roughy",
      "Saglutupiaġataq",
      "National Grand Mal Seizure",
      "Champion of Oppressors",
      "Angry Postule",
      "Dolt 45",
      "Combover Caligula",
      "Mango Manchurian",
      "Idiot Amin",
      "Twitler",
      "Der Gropenführer",
      "Cheez Whiz Ceaușescu",
      "Passionfruit Pinochet",
      "Darth Hater",
      "Lord Goldemort",
      "Littlefingers",
      "Mango Chucky",
      "Tangerine Torquemada",
      "Sociopathic Potato",
      "Boss Tweet",
      "Marmalade Mussolini",
      "Furious Orange",
      "Cheeto Golem",
      "Jack the Twitter",
      "Lyssavirus Agglutination",
      "Tribble Mobility Scooter",
      "Con Fartiste",
      "Pinochetio",
      "Tribble Threat",
      "Saffron Suharto",
      "Manchurian Manchild",
      "Pyschopathic Elmer Fudd",
      "Orange Woundwort",
      "Dorito Mussolini",
      "Neon Nero",
      "Reliable Emetic",
      "Emperor Tangerine McTinyhands",
      "Narcissist-in-Chief",
      "Bannon's Burnt Orange Marionette",
      "Know-Nothing",
      "Commander-in-Cheat",
      "Putin Pony",
      "Walking, Talking SNL Cold Open",
      "Super Callous Fragile Racist Sexist Nazi POTUS",
      "STD That Won't Respond to Antibiotics",
      'Wussolini',
      'Tropicana Jong Il',
      'Off-Brand Nixon',
      'Sartorially Challenged Canteloup',
      'Melania\'s Future Ex-Husband',
      'Saruman the Orange',
      'Yamchurian Candidate',
      'Abscessed Tooth',
      'Mousseolini',
      'Dump Truck',
      'Yellow Snowflake',
      'Festering Sore on Democracy',
      'Bag of Farts',
      'Whiny Twitter Addict',
      'Permanent Toothache',
      'Miserable Bastard',
      'Catsup Covered Well-Done Strip Steak',
      'Fake Billionaire',
      'Tangerine-Tinted Trash Fire',
      'Spongebob Dictator-Pants',
      'Deadly Blob of Melted Nuclear Fuel',
      'Ball of Hair and Dust Mites Clogging your Vacuum',
      'Vanity Hair',
      'Haunted Toenail Clipping',
      'Milk-Faced Popinjay',
      'Dunning-Kruger Singularity',
      'King Leer',
      'Sheriff of Rottingham',
      'King Joffrey the Treasonous',
      'Chicken-Necked Scumbag',
      'Orange Foolius',
      'Worst Person Ever',
      'Don Corleorange',
      'Great Crested Traffic Barrel',
      'Deranged Dotard',
      'Moron-in-Chief',
      'Worst Possible Person to be President',
      'Desperate Wet Cheeto',
      'Donny Two-Scoops',
      'World\'s Oldest Toddler',
      'Tangerine Idi Amin',
      'Just a Big 💩',
      'Son of a Brothel Goat',
      'Yellow #6',
      'Five-Deferment Draft Dodger',
      'Cadet Bone Spurs',
      'Florida Man',
      'Blessedly Incompetent Person',
      'Drum of Hot Farts',
      'Reverse Midas',
      'Roadside Urine Jug',
      'IQ45',
      'Corncob Head',
      'Victim of Tanning Bed Malfunction',
      'Baked Ham',
      'Liar-in-Chief',
      'Mango Mugabe',
      '45✱',
      'Horse Loose in a Hospital',
      'Corporal Bone Spurs',
      'Orange Colostomy Bag',
      'King Mierdas',
      '💩',
      "The Very Last Person on Earth Who You'd Want to Be President",
      'Agent Orange',
      'Mt. St. Felons',
      'Gassy Burrito',
      'Lord of the Fries',
      'Lord Peeington',
      'Blonde Dingleberry',
      'Wee-Wee Dinkypaws',
      'White Noise Machine',
      'Traitor in Chief',
      'Most Corrupt President Ever',
      'Пу́тин кукольный',
      'TЯЦMР',
      'Shrieking Toad',
      'TraitorTot™',
      'Talking Gallstone',
      'Ungainly Chicken of Late-Stage Capitalism Come Home To Roost',
      'Individual 1',
      'Felon-in-Chief',
      'Fredo Corleone',
      'Mottled Rump',
      'Swamp Creature',
      'Underlying Crime',
      'Walking Obstruction of Justice',
      'Despicable Him',
      'Simpering Worm',
      'Rubber Duck Dipped in Vinegar',
      'Vain, Cancerous Tumor',
      'Tweeto von Cheeto',
      'Poll Rot',
      'Cheez-Whiz Musharraf', 
      'Apricot Al-Assad',
      'Mango Milosevic',
      "Satan's Worst Minion",
      'Abomination-in-Chief',
      'Hell, Manifested on Earth',
      'Twitter Account Come to Life',
      'Kumquat Pol Pot',
      'Impeached Rotten Peach',
    ],
    'dirty': [
      "Fuckface von Clownstick",
      "Billionaire and Person Who, Having Won the Fucking Presidency Without Any Qualifications, Inexplicably Believes the World is Set Against Him",
      "Political Ass Clown",
      "Vacuous Dipshit",
      "Degloved Zoo Penis",
      "Shithead",
      "Orange Asshat",
      "Idiot Cockwomble",
      "Ludicrous Tangerine Ballbag",
      "Incompressible Jizztrumpet",
      "Ferret-Wearing Shitgibbon",
      "Witless Fucking Cocksplat",
      "Buttplug Face",
      "Toupeed Fucktrumpet",
      "Human Turd",
      "High Oracle of Dipshittery",
      "Anus Lips",
      "Foul-Mouthed Tit Judge",
      "Baboon Anus",
      "Orange Condom Filled with Rancid Stew",
      "Used Diaphragm from the Jersey Shore",
      "Human Queef",
      "Noted Chode",
      "Man Whose Head Firmly Resembles a Lone Radioactive Testicle Sealed in a Jar of Formaldehyde",
      "Weeping Herpe Sore",
      "Donald Putinobitch",
      "Il Douche",
      "Goldman's Sack",
      "Dick l'Orange",
      "Badhair al-Asshead",
      "Garfield's Scrotal Cancer",
      "Cockjerk Orange",
      "Blithering Butthole",
      "Scrooge McFuck",
      "America's #2",
      "Lord Dampnut",
      "Your Shitty Racist Uncle",
      "Twitshitter",
      "Gaseous Pompous Ass",
      "Sunburned Puckered Asshole",
      "Fart That Turned out to Be a Shit",
      "Dicktator",
      'Urine Bather',
      'Generalassimo',
      'Asshole-in-One',
      'Bergamot Ballsack',
      'Fucking Moron',
      'Fucky McFuckface',
      'Utter Prick',
      'Smegma Goblin',
      "America's Pulsing Sphincter",
      'Pussygrabber Galore',
      'Spraytan Sphincterlips',
      'Shit-Midas',
      "America's Shitstorm",
      'Unwiped Ass-Crack',
      'Shit You Just Stepped In',
      'Genital Wart',
      'Dumbass Twatwaffle',
      'Pendejo Naranja',
      'Baby Dick',
    ],
  },
  'alt-right': {
    'clean': [
      "Alt-Very-Wrong",
      "Serioualy-These-Are-Bad-People-Right",
      "Rebranded-White-Nationalist-Cult",
      "Hate-Filled-Right",
      "White-Supremacist-Movement",
      "Racist-Lunatic-Right",
      "Anti-Semitic-Monsters",
      "Misogynist-Cult",
      "Oft-Wrong",
      "Confederacy-of-Psychopathic-Dunces",
      "White-Nationalist-Fanboys",
      "Bowel Movement",
      "Always-Wrong",
      "Bass-Ackward-Bigotry",
      "Real-Special-Snowflakes",
      'Postules-of-Hate',
      'Melting-Snowflake',
      'Alt-Blight',
      'Projecting-Snowflakes',
      'Nazis-with-Memes',
      'Hateful Man-Babies',
      'Dunciad of Confederates',
      'So-So-Wrong',
    ],
    'dirty': [
      "Fucking-Scary-Right",
      'Anal-Rot',
    ],
  },
  'pence': {
    'clean': [
      "Dead-Ended Politician with Apparently Very Little to Lose",
      "Man Who Has Probably Tried To Outlaw Dancing",
      "Champion of Homophobic Pizza Makers",
      "Numbnuts Sidekick",
      "Total Failure as a Congressman",
      "Emcee Pink",
      "I'm with Stupid",
      "Focus of Chris Christie's Unrelenting Jealous Rage",
      "Mini-Bigot",
      "Supposedly Solid, Solid Person",
      "Rush Limbaugh on Decaf, Except Never Funny",
      "Six Term Congressman with Perfect Record of Writing Zero Bills that Became Law",
      "Angry Second-Assistant High School Football Coach",
      "Person Correct About Global Warming, Probably, in Some Distant Parallel Universe",
      "Man to Be Remembered Primarily for His Willingness to Be Associated with Donald Trump",
      "Conservative-Looking Guy Sent from Central Casting",
      "Presidential Apprentice",
      "Closeted Bottom",
      "Walking Precious Moments Figurine",
      'Homophobic Scout Leader',
      'Moldy Nilla Wafer',
      'Misogynistic Bowl of Oatmeal',
      'Rejected Square',
      'Permanently Constipated Man',
      "America's #2",
      'Warren Harding Impersonator',
      "Mother's Favorite Little Soldier",
      '"Mother" Lover',
      'Norman Bates Double',
    ],
    'dirty' : [
    ],
  },
  'bannon': {
    'clean' : [
      'Whiskey-Soaked Machiavelli',
      'Unshaven Emperor Palpatine',
      'Goebbels Acolyte',
      'Coke-Addled Dorito-Huffing Rasputin',
      'Fascist Puppeteer',
      'Plotter Against America',
      'Constitutional Demolitions Director',
      'White Nationalist Potato Sack',
      'Shiva, Destroyer of Rights',
      'Man Who, in a Sane Universe, Would Warm a Barstool Alone Every Night Before Returning to His Empty Trailer',
      "Rumpled Suit With The President's Ear",
      'Leader of the Leader of the Free World',
      'Bigot Whisperer',
      'White Supremacist Beanbag',
      'Orangutan Keeper',
      'Pre-Ghost Version of Slimer',
      'Person Who Looks like He Pukes More Than He Showers',
      "Art Student's Attempt at Sculpting Robert Redford Out of Room Temperature Tapioca",
      "Baron Harkonnen's Origin Story",
      'Actual Grinch',
      'Guy Infected with Zombie Virus that Tried to Hide It',
      'MacGyver without Epi-Pen, Stung in the Face by a Bee',
      "Man One Pizza Away from his Next Papa John's Order Free",
      'Garbage Pail Kid',
      'Bread Dough Requiring a Punch-Down',
      'Best-Looking Man in The Liquor Store at 1 AM',
      'The Disease AIDS Would Catch If It Were Promiscuous and Careless for Decades',
      'Furry Turned Inside-Out',
      'Rash Wearing a Jabba Costume',
      'Zombie Mark Hamill',
      'Alcoholic Ewok',
      'Chief White Supremacy Strategist',
      'Phantom Menace',
      'Eczema Made Human',
      'Satellite Image of Storm on Jupiter',
      'Vader Wannabe',
      'Resurrected Roadkill',
      'Actual Racist',
      'Hate-Filled Troll With a Plan',
      "Besuited Racist Pig",
      'Ghostbusters Containment System Escapee',
      'Racist Hemorrhoid',
      'Bag of Wet Cigarette Butts',
      'Gin Blossom Gone to Seed',
      'Flea Market Made Flesh',
      'Sack of Halitosis',
      'Cirrhotic Rasputin',
      'Seething 4chan Post',
      'Spoiled Lard Blob Stuck to the Botom of the Recycle Bin',
      'Soiled Fish Tank Filter Insert',
      'Bannon Hackonnen',
      'Three Day Old Corpse Just Pulled from River',
      'Diseased Bullfrog',
    ],
    'dirty': [
      'Neo Nazi Dickhead',
      'Repulsive, Plotting Shit',
      'Twenty Pounds of Shit in a Ten Pound Sack',
      'Reeking Smegma',
      'Tanker Truck of Ass Sweat',
    ]
  },
  'sessions': {
    'clean': [
      'Man Too Racist For Strom Thurmond',
      'Evil Yoda',
      'Perjurer General',
      "Staunch Defender of Jeff Sessions's Civil Rights",
      "Child Who Was Turned Into an Old Man for Stealing a Pie from A Witch's Windowsill",
      'Keebler Elf',
      'Tiny Racist',
      'Compact Klansman',
      'Full-Size Evil in a Travel-Size Container',
      'Klansman / Leprechaun Love Child',
      'Lucky Charms Mascot',
      'Ku Klux Keebler',
      'Apple-Cheeked Hate Goblin',
      'Blob of Raw Cookie Dough',
    ],
    'dirty': [
    ],
  },
  'conway': {
    'clean' : [
      'Empty Shell That Might Once Have Been Occupied by a Human',
      'Alternative Fact Peddler',
      'Kellyanne Con-Artist',
      'Deputy Assistant Trump Boot Licker',
      'Suspected Trump Hostage',
      'Expert Liar',
      'Truth Mutilator',
      'Word Salad Dressing',
      'Robot Sent From The Future to Obliterate The Very Idea of Shared Reality',
      'Rhetorical IED',
      'Tennis Machine of Lies',
      'Nonstop Liar',
      'Lying Ear of Dessicated Corn',
      'Con-Job',
    ],
    'dirty' : [
      "Shitstorm's Chamber Maid",
    ],
  },
  'spicer': {
    'clean': [
      'Mouth of Sauron',
      'Crack Hamster',
      'Dissembly Secretary',
      'Man Who Permanently Destroyed All Credibility on First Day of Job',
      'Official Tweet Elaborator',
      'Trumpsplainer',
      'Whiny Spice',
      "America's Baghdad Bob",
      'Human Toilet Brush',
      'Man Hiding in Bushes',
    ],
    'dirty': [
      'Sean Sphincter',
      'Bullshit Spice',
    ],
  },
  'ryan': {
    'clean': [
      'Granny Starver',
      'What Passes for a Serious Policy Wonk in Republican-Land',
      'Professional Sad Puppy Face',
      'International Man of Principle and Integritude',
      'Mercifully Incompetent Evil House Speaker',
      'Eddie Munster Understudy',
      "Ol' Zombie-Eyes",
    ],
    'dirty': [
      'The Honorable Mr. Fuck You I Got Mine',
      'Spineless Shitweasel',
    ],
  },
  'gorsuch': {
    'clean': [
      'Asterisk',
    ],
    'dirty': [
    ],
  },
  'mcconnell': {
    'clean': [
      'Human/Turtle Hybrid',
      'Yertle the Turtle',
      'Lipless Turtle',
      "Donatello's Racist Uncle",
      'Actual Grinch',
      'Dixie Koopa',
      'Comrade Turtleface',
      'Constitutional Demolitions Expert',
      'Moscow Mitch',
    ],
    'dirty': [
    ],
  },
  'breitbart': {
    'clean': [
      'Blightshart',
      'Notsmart',
      'Spitefart',
      'Not-So-Brightbart',
    ],
    'dirty': [
    ],
  },
  'shuckabee': {
    'clean': [
      'Sarah Huckster Sanders',
      'Spawn of Mike Huckabee',
      'Un-❤-able Huckabee',
      'Baghdad Barbie',
      'Sneer of Sauron',
    ],
    'dirty': [
      'Lying White House Spokesperson Number n+1',
      'Another Mendacious Sack of Shit',
    ],
  },
  'kelly': {
    'clean': [
        'Formerly Respected General Who Traded That All In To Carry Water for This Jackass',
        'Man Who Lectures Gold Star Families With Heartfelt Bullshit',
    ],
    'dirty': [
    ],
  },
  'devos': {
    'clean': [
      'Cruella DeVos',
      'DevOs Umbridge',
      'Dumbridge',
      'Uneducated Human Eraser',
      'Educational Allergy',
      'Calvinist Thief',
    ],
    'dirty': [
    ],
  },
  'pai': {
    'clean': [
        'FCC Con Artist',
        'Comcast, if it Were a Human,',
        'Walking Bad WiFi Connection',
        'Rotten Pai',
        'Net Neuterer',
    ],
    'dirty': [
        'Comcast Fellator',
        'A Shit Pie',
    ],
  },
  'kavanaugh': {
    'clean': [
        'Federalist Society Angry Robot',
        'Raging Spittle-Sprayer',
        "Bart O'Kavanaugh",
        'Probable Rapist',
        'Mean Drunk',
        'Textbook Alcoholic',
        'Beer Liker',
        'Serial Perjurer',
        'Sunofabitch Who Thinks Supreme Court Seat Is His Birthright',
        'Soon-to-be Passengerless Carpool Dad',
        'Future Convict',
        'Prep-School Douchebag',
        'Boofoon',
        'Hostile White Man Unaccustomed to Slightest Bit of Accountability',
        'Walking Alcoholics Anonymous PSA',
        'Yalie MacYaleface',
        'Kava-Nope',
        'Loud, Annoying Drunk',
    ],
    'dirty': [
        'Drunken Dick Waver',
        'Sexist Fuckwit',
        'Just Another Shitbag from Yale',
        'Sexist, Drunk Jackass',
    ],
  },
  'giuliani': {
    'clean': [
      "America's (Worst) Mayor",
      'Butt Only Good For Dialing',
      "Ol' Yeller",
      'Kind of a Lawyer, We Guess',
      'Dumbassador to Ukraine',
      'Prosecutor Turned Mobster',
      'Shakedown Man',
    ],
    'dirty': [
    ],
  },
  'ivanka': {
    'clean': [
      'Daughter Wife',
      'Nepotism Barbie',
      'Real First Lady',
      "Daddy's Little Ghoul",
      'Proxy Wife',
      'Ivanka the Terrible',
      'Trophy Daughter',
      'Out-of-Touch Barbie',
      'Crown Princess Complicity',
      "Daddy's Favorite Griftress",
    ],
    'dirty': [
      "Person Who's Pussy has Special No-Grab Privileges"
    ],
  },
  'hannity': {
    'clean': [
      'Mister Bad-For-America Himself',
      'The REAL Fake News Journalist',
      'Fake News Fount',
      "Putin's Favorite Spy",
      "Lead Trump Fluffer",
    ],
    'dirty': [
      "Ted Koppel's Bitch",
    ],
  },
  'zuckerberg': {
    'clean': [
      'Face 💩',
      'MySpace Murderer',
      'Man Whose Virgin Level, In A Sane Universe, Would Be Over 9000',
      'Just Another CIA Agent With A Particular Set Of H4CK0R $K1LLZ',
      'Dead-Eyed Zombie',
    ],
    'dirty': [
      'Facefuck',
    ],
  },
  'dorsey': {
    'clean': [
      'Top Twit',
      'Number-One Trending Topic In His Own Mind'
    ],
    'dirty': [
      'Shitter',
      '#asshole',
      '#motherfucker',
    ],
  },
  'mclaughlin': {
    'clean': [
      'Not My Pollsters',
      '2016 Election Fixers',
      'Man Voted Most Likely To Be Mind-Controlled By Putin',
    ],
    'dirty': [
    ],
  },
}

url_base = 'https://toolsofourtools.org/detrumpify2/v2/'

combos = {
    'disable.json': {
        'monikers': [],
        'matic': [],
        'button': {
            'name': 'Disable Detrumpify',
            'description': 'Temporarily disable Detrumpify',
        },
    },
    'combined.json': {
        'monikers': ['clean', 'dirty'],
        'matic': { 
            'a': ['clean', 'dirty'], 
            'b': ['clean', 'dirty' ],
            'shka': ['clean', 'dirty' ],
            'shkb': ['clean', 'dirty' ],
            'shkc': ['clean', 'dirty' ],
        },
        'button': {
          'name': 'clean + NSFW insults',
          'description': 'Combined list of clean and dirty names.',
        },
    },
    'clean.json': {
        'monikers': ['clean', ],
        'matic': { 
            'a' : ['clean', ], 
            'b': ['clean', ],
            'shka': ['clean', ],
            'shkb': ['clean', ],
            'shkc': ['clean', ],
        },
        'button': {
          'name': 'clean insults',
          'description': 'Clean names only.',
        },
    },
    'dirty.json': {
        'monikers': ['dirty', ],
        'matic': { 'a' : ['clean', 'dirty'], 'b': ['dirty' ] },
        'button': {
          'name': 'NSFW insults',
          'description': 'Only curseword names.'
        },
    },
}

for comboname in combos:

    outdata = copy.deepcopy(base)
    empty_actions = []
    for person in monikers:
      outdata['actions'][person]['monikers'] = []

      if person in matic:
          outdata['actions'][person]['matic'] = {
              'slots': {},
              'recipe': matic[person]['recipe'],
          }
          for matic_slot in combos[comboname]['matic']:
              outdata['actions'][person]['matic']['slots'][matic_slot] = []

              for slot_group in combos[comboname]['matic'][matic_slot]:
                  for entry in matic[person][slot_group]['slots'][matic_slot]:
                      outdata['actions'][person]['matic']['slots'][matic_slot].append(entry)


      for moniker_group in combos[comboname]['monikers']:
        for moniker in monikers[person][moniker_group]:
          max_len = combos[comboname].get('max_len',0)
          if max_len:
              act_len = len(re.split(r'[\s\-]',moniker))
              if act_len <= max_len:
                  outdata['actions'][person]['monikers'].append(moniker)
          else:
              outdata['actions'][person]['monikers'].append(moniker)

      for v in ['randomize_mode', 'match_style', 'match_class', 'bracket']:
        if v in combos[comboname]:
          outdata['actions'][person][v] = combos[comboname][v]

      if len(outdata['actions'][person]['monikers']) < 1:
        empty_actions.append(person)

    # remove actions with no insults
    for person in empty_actions:
      outdata['actions'].pop(person,None)

    if False:
        # remove actions that are not quite ready for prime time
        for person in ['conway','spicer']:
            outdata['actions'].pop(person,None)

    jsd = json.dumps(outdata)
    ofile = open(comboname, 'w')
    ofile.write(jsd)
    ofile.close()

ofile = open("insults.txt", "wb")
for moniker in sorted(monikers['trump']['clean']):
    ofile.write(''.join(['"',moniker,'",',"\n"]).encode('utf-8'))
ofile.close()


## button config file
bconfig = []
for comboname in combos:
  combos[comboname]['button']['url'] = url_base + comboname
  bconfig.append(combos[comboname]['button'])

bconfig.append({
  'name': 'Drumpf',
  'url': url_base + 'drumpf.json',
  'description': 'Always Drumpf (John Oliver mode)'
});
bconfig.append({
  'name': 'Drumpf',
  'url': url_base + 'individual1.json',
  'description': 'Individual 1'
});
bconfig.append({
  'name': 'Lord Dampnut',
  'url': url_base + 'dampnut.json',
  'description': 'Always "Lord Dampnut"'
});
bconfig.append({
  'name': 'Just Pictures',
  'url': url_base + 'justpictures.json',
  'description': 'No Insults -- Just Pictures',
});
bconfig.append({
  'name': 'NZ Black it Out - Counter Hate',
  'url': url_base + 'blackout.json',
  'description': 'NZ Black it Out - Counter Hate',
});


ofile = open('buttons_config.json',"w")
ofile.write(json.dumps(bconfig))
ofile.close()

